// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package modelpg

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("CartItems", testCartItemsUpsert)

	t.Run("Carts", testCartsUpsert)

	t.Run("Deliveries", testDeliveriesUpsert)

	t.Run("DeliverySessions", testDeliverySessionsUpsert)

	t.Run("Locations", testLocationsUpsert)

	t.Run("OrderItems", testOrderItemsUpsert)

	t.Run("OrderSessions", testOrderSessionsUpsert)

	t.Run("Orders", testOrdersUpsert)

	t.Run("Payments", testPaymentsUpsert)

	t.Run("Products", testProductsUpsert)

	t.Run("ShopBankCards", testShopBankCardsUpsert)

	t.Run("Shops", testShopsUpsert)

	t.Run("StockKeepingUnits", testStockKeepingUnitsUpsert)

	t.Run("UserBankCards", testUserBankCardsUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("WarehouseBankCards", testWarehouseBankCardsUpsert)

	t.Run("Warehouses", testWarehousesUpsert)
}
